development:
  adapter: postgresql
  encoding: unicode
  database: deve_db
  pool: 5
  username: developer
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: test_db
  pool: 5
  username: postgres 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: prod_db 
  pool: 5
  username: production 
  password:
